name: tests ddev-kibana

on:
  pull_request:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' #semantic version format

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Debug with tmate set "debug_enabled"'
        required: false
        default: "false"

defaults:
  run:
    shell: bash

permissions:
  actions: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: "janopl/ddev-kibana"
  TEST_PATH: .

jobs:
  tests:
    name: tests
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        ddev_version: [ stable ] # ddev_version: [stable, edge, HEAD, PR]
        os: [ubuntu-24.04] # os: ubuntu-20.04, ubuntu-22.04, macos-12, macos-11, ubuntu-latest, macos-latest, windows-2019, windows-2022, windows-latest
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: kibana image
        run: |
            docker pull ghcr.io/janopl/ddev-kibana/kibana-sync:7.17.14 >/dev/null
            docker pull ghcr.io/janopl/ddev-kibana/kibana-sync:8.10.2 >/dev/null
            docker pull ghcr.io/janopl/ddev-kibana/kibana-sync:9.3.3 >/dev/null

      - uses: ddev/ddev-add-on-test@v2
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ env.GITHUB_REPOSITORY }}
          addon_ref: ${{ env.ADD_ON_LAST_TAG }}
          addon_path: ${{ env.TEST_PATH }}
          disable_checkout_action: false
          test_command: 'bats --timing tests/addon_dep_check.bats tests/validate_project_files.bats tests/test_local.bats tests/test_local_version_7.bats tests/test_local_version_8.bats'
